### ISSUE TITLE
Can't get GMN to train on MNIST INR classification

### ISSUE THREAD

**Issue by AvivNavon** [jkalogero/scalegmn#4]
Hi, I'm following the readme instructions to run GMN on the MNIST INR classification task. After preparing the data, I'm running:
`python inr_classification.py --conf configs/mnist_cls/scalegmn.yml --scalegmn_args.symmetry=permutation`
However, the model is unable to learn and only achieves random performance (~11% accuracy). 

I'll appreciate any help, thanks 🙏

**Comment by jkalogero** [comment]
Hello @AvivNavon,

We also encountered this issue when experimenting with GMN (i.e., accounting only for _permutation_ symmetries).

I believe the problem arises because for ScaleGMN we do not normalize the input weights, as standard normalization (e.g., mean and standard deviation) is not scale equivariant. However, since you focus only on permutations, you can still apply a normalization like in [DWS](https://github.com/AvivNavon/DWSNets/) or [neural-graphs](https://github.com/mkofinas/neural-graphs/). Doing so seems to solve the issue and running `python inr_classification.py --conf configs/mnist_cls/scalegmn.yml --scalegmn_args.symmetry=permutation` works great. **Note**: Normalization is currently not included in this repo, but it is straightforward how to integrate it.

While ScaleGMN did not lead to this problem under all the tested configurations, we tried a hyperparameter search for GMN w/o normalization to see if this problem persists. Indeed, there were a few cases where the model was able to learn and even perform on par with GMN w/ normalization, but I was unable to identify any consistent pattern.

Let me know if you are still having any issues.

**Comment by AvivNavon** [comment]
That makes sense, thanks @jkalogero !
